package com.example.ultraman

import com.example.ultraman.model.ListUltraman

val ultramans = listOf(
    ListUltraman(1, "Ultraman Noa", "Kazuki Komon", "55 m", "55,000 t", "Ultraman Noa (ウルトラマンノア, Urutoraman Noa) is an ancient Ultraman from the World of N who pursued his evil counterpart, Dark Zagi, throughout various universes and countless alien worlds, including the World of the Land of Light. He is an Ultra who has been active across the multiverse gaining the moniker of a legendary figure for his power and feats. Noa is also the true form of Ultraman the Next/Ultraman Nexus.", "https://th.bing.com/th/id/OIP.1rd_goNDK6agE1vRe4AMyAHaKX?rs=1&pid=ImgDetMain", "https://ultra.fandom.com/wiki/Ultraman_Noa"),
    ListUltraman(2, "Ultraman Nexus", "Kazuki Komon", "49 m", "40,000 t", "Ultraman Nexus (ウルトラマンネクサス, Urutoraman Nekusasu) is Ultraman Noa's second devolved form, and is the form a Dunamist assumes after using the Evoltruster. Starring in Ultraman Nexus, his story represented as the final phase of Ultra N Project. After evolving from Ultraman the Next, Nexus would resurface in 2008 to fight against a wave of Space Beast assaults, slowly growing in strength after bonding with multiple Dunamists and finally regaining his long lost form Ultraman Noa in his battle with Dark Zagi.", "https://pbs.twimg.com/media/FVhSSBHagAAWSju.jpg", "https://ultra.fandom.com/wiki/Ultraman_Nexus_(character)"),
    ListUltraman(3, "Ultraman Mebius", "Mirai Hibino", "49 m", "35,000 t", "Ultraman Mebius (ウルトラマンメビウス, Urutoraman Mebiusu) is the protagonist of the eponymous series Ultraman Mebius. He was sent to Earth 25 years after Ultraman 80 to protect the planet from a new wave of monsters and aliens, many of which arrived due to Alien Empera's resurgence. During his tenure on Earth, he took the form of Mirai Hibino, and joined Crew GUYS.", "https://pbs.twimg.com/media/FVhVh22akAA69s3.jpg", "https://ultra.fandom.com/wiki/Ultraman_Mebius_(character)"),
    ListUltraman(4, "Ultraman Tiga", "Daigo Madoka", "Micro ~ 53 m", "44,000 t", "Ultraman Tiga (ウルトラマンティガ, Urutoraman Tiga) is the eponymous Ultra Hero of Ultraman Tiga. He is notable for being the first Ultraman in the franchise to be able to change forms, as well as being the first Ultra to appear in a televised series since Ultraman 80, ending a 15-year semi-hiatus.", "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/aad45e4a-312a-469e-b82d-3dc010e4a687/dfofafd-cc54df22-844a-424d-b730-af3c8caee3d3.jpg/v1/fill/w_1280,h_2157,q_75,strp/ultraman_tiga_dark_and_multi_by_ultrahorizongax2021_dfofafd-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MjE1NyIsInBhdGgiOiJcL2ZcL2FhZDQ1ZTRhLTMxMmEtNDY5ZS1iODJkLTNkYzAxMGU0YTY4N1wvZGZvZmFmZC1jYzU0ZGYyMi04NDRhLTQyNGQtYjczMC1hZjNjOGNhZWUzZDMuanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.jr6D72YJG31Qebrxa5bYWDHfdcOfVQ4Rx6Dy3fu-Lqw", "https://ultra.fandom.com/wiki/Ultraman_Tiga_(character)"),
    ListUltraman(5, "Ultraman Belial", "Arie Ishikari", "55 m", "60,000 t", "Ultraman Belial (ウルトラマンベリアル, Urutoraman Beriaru) was an evil Ultraman from the Land of Light, who was best known as Ultraman Zero's arch enemy and the father of Ultraman Geed. He was once a great fighter who took part in the Ultimate Wars, but his pride and greed got the better of him. This ultimately led him to commit the heinous crime of attempting to steal the Plasma Spark, for which he was banished. Injured and cast out, Belial was approached and transformed by Alien Reiblood into a Reionics, forever turning him to the darkness.\n" +
            "Belial seemingly met his final end at the hands of his synthetic son, Ultraman Geed, in a climactic final battle that decided the fate of the universe. However, his existence continues to send ripples through the multiverse in the form of the Devil Splinters derived from his cells, as well as a parallel version of himself who lives on in the present day, having had his fate forever changed by a chance encounter with Absolute Tartarus.", "https://tsuburaya-prod.com/wp-content/uploads/2019/12/berial2.jpg", "https://ultra.fandom.com/wiki/Ultraman_Belial"),
    ListUltraman(6, "Ultraman Zero", "Run (ラン, Ran)", "Micro ~ 49 m", "35,000 t", "Ultraman Zero (ウルトラマンゼロ, Urutoraman Zero) is the son of Ultraseven. He was trained under Ultraman Leo after he was banished from the Land of Light by his father for attempting to take the Plasma Spark for himself. His training ultimately led to his redemption in his battle with Belial.\n" +
            "Zero is one of the most popular Ultras in the Ultraman Series' history, appearing many times over a decade since his debut.", "https://th.bing.com/th/id/OIP.E9iggNICwtyI7UR4WSD-1wHaKm?rs=1&pid=ImgDetMain", "https://ultra.fandom.com/wiki/Ultraman_Zero")
)